name: UE Programmation - Laval 3di

# -------------------------------------------------------
# Globals.
# -------------------------------------------------------

show_drafts: nil
permalink: /:title/

include: ['_pages']
exclude: ['README.md', 'LICENSE', 'package.json', 'gulpfile.js', 'node_modules', 'Gemfile', 'Gemfile.lock']

excerpt_separator: <!--more-->

# -------------------------------------------------------
# Collections.
# -------------------------------------------------------

collections:
  pico8:
    output: true
    permalink: /pico8/:title/
  csharp:
    output: true
    permalink: /csharp/:title/

# -------------------------------------------------------
# Defaults.
# -------------------------------------------------------

defaults:
  - scope:
      path: ""
      type: "pages"
    values:
      layout: "default"
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  - scope:
      path: ""
      type: "code"
    values:
      layout: "post"
  - scope:
      path: ""
      type: "projects"
    values:
      layout: "post"
  - scope:
      path: ""
      type: "events"
    values:
      layout: "post"

# -------------------------------------------------------
# Markdown.
# -------------------------------------------------------

kramdown:
  input: GFM
  parse_block_html: true
  parse_span_html: true

# -------------------------------------------------------
# Code.
# -------------------------------------------------------

highlighter: rouge

# -------------------------------------------------------
# Plugins.
# -------------------------------------------------------

gems:
  - jekyll-redirect-from
